/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MlEvaluationRouteImport } from './routes/ml-evaluation'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SoilAnalysisRouteImport } from './routes/soil-analysis'
import { Route as ApiPredictRouteImport } from './routes/api/predict'
import { Route as AppointmentsIndexRouteImport } from './routes/appointments.index'
import { Route as AppointmentsBookRouteImport } from './routes/appointments.book'
import { Route as CultivationIndexRouteImport } from './routes/cultivation.index'
import { Route as CultivationCropRouteImport } from './routes/cultivation.$crop'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as RecommendationsIndexRouteImport } from './routes/recommendations.index'
import { Route as RecommendationsCompareRouteImport } from './routes/recommendations.compare'
import { Route as SoilReportsIndexRouteImport } from './routes/soil-reports.index'
import { Route as SoilReportsIdRouteImport } from './routes/soil-reports.$id'
import { Route as SoilTestingIndexRouteImport } from './routes/soil-testing.index'
import { Route as SoilTestingProviderIdRouteImport } from './routes/soil-testing.$providerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MlEvaluationRoute = MlEvaluationRouteImport.update({
  id: '/ml-evaluation',
  path: '/ml-evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SoilAnalysisRoute = SoilAnalysisRouteImport.update({
  id: '/soil-analysis',
  path: '/soil-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPredictRoute = ApiPredictRouteImport.update({
  id: '/api/predict',
  path: '/api/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsBookRoute = AppointmentsBookRouteImport.update({
  id: '/appointments/book',
  path: '/appointments/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CultivationIndexRoute = CultivationIndexRouteImport.update({
  id: '/cultivation/',
  path: '/cultivation/',
  getParentRoute: () => rootRouteImport,
} as any)
const CultivationCropRoute = CultivationCropRouteImport.update({
  id: '/cultivation/$crop',
  path: '/cultivation/$crop',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsIndexRoute = RecommendationsIndexRouteImport.update({
  id: '/recommendations/',
  path: '/recommendations/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsCompareRoute = RecommendationsCompareRouteImport.update({
  id: '/recommendations/compare',
  path: '/recommendations/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const SoilReportsIndexRoute = SoilReportsIndexRouteImport.update({
  id: '/soil-reports/',
  path: '/soil-reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoilReportsIdRoute = SoilReportsIdRouteImport.update({
  id: '/soil-reports/$id',
  path: '/soil-reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SoilTestingIndexRoute = SoilTestingIndexRouteImport.update({
  id: '/soil-testing/',
  path: '/soil-testing/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoilTestingProviderIdRoute = SoilTestingProviderIdRouteImport.update({
  id: '/soil-testing/$providerId',
  path: '/soil-testing/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/ml-evaluation': typeof MlEvaluationRoute
  '/register': typeof RegisterRoute
  '/soil-analysis': typeof SoilAnalysisRoute
  '/api/predict': typeof ApiPredictRoute
  '/appointments/book': typeof AppointmentsBookRoute
  '/cultivation/$crop': typeof CultivationCropRoute
  '/history/$id': typeof HistoryIdRoute
  '/recommendations/compare': typeof RecommendationsCompareRoute
  '/soil-reports/$id': typeof SoilReportsIdRoute
  '/soil-testing/$providerId': typeof SoilTestingProviderIdRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/cultivation/': typeof CultivationIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/recommendations/': typeof RecommendationsIndexRoute
  '/soil-reports/': typeof SoilReportsIndexRoute
  '/soil-testing/': typeof SoilTestingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/ml-evaluation': typeof MlEvaluationRoute
  '/register': typeof RegisterRoute
  '/soil-analysis': typeof SoilAnalysisRoute
  '/api/predict': typeof ApiPredictRoute
  '/appointments/book': typeof AppointmentsBookRoute
  '/cultivation/$crop': typeof CultivationCropRoute
  '/history/$id': typeof HistoryIdRoute
  '/recommendations/compare': typeof RecommendationsCompareRoute
  '/soil-reports/$id': typeof SoilReportsIdRoute
  '/soil-testing/$providerId': typeof SoilTestingProviderIdRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/cultivation': typeof CultivationIndexRoute
  '/history': typeof HistoryIndexRoute
  '/recommendations': typeof RecommendationsIndexRoute
  '/soil-reports': typeof SoilReportsIndexRoute
  '/soil-testing': typeof SoilTestingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/ml-evaluation': typeof MlEvaluationRoute
  '/register': typeof RegisterRoute
  '/soil-analysis': typeof SoilAnalysisRoute
  '/api/predict': typeof ApiPredictRoute
  '/appointments/book': typeof AppointmentsBookRoute
  '/cultivation/$crop': typeof CultivationCropRoute
  '/history/$id': typeof HistoryIdRoute
  '/recommendations/compare': typeof RecommendationsCompareRoute
  '/soil-reports/$id': typeof SoilReportsIdRoute
  '/soil-testing/$providerId': typeof SoilTestingProviderIdRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/cultivation/': typeof CultivationIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/recommendations/': typeof RecommendationsIndexRoute
  '/soil-reports/': typeof SoilReportsIndexRoute
  '/soil-testing/': typeof SoilTestingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/ml-evaluation'
    | '/register'
    | '/soil-analysis'
    | '/api/predict'
    | '/appointments/book'
    | '/cultivation/$crop'
    | '/history/$id'
    | '/recommendations/compare'
    | '/soil-reports/$id'
    | '/soil-testing/$providerId'
    | '/appointments/'
    | '/cultivation/'
    | '/history/'
    | '/recommendations/'
    | '/soil-reports/'
    | '/soil-testing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/ml-evaluation'
    | '/register'
    | '/soil-analysis'
    | '/api/predict'
    | '/appointments/book'
    | '/cultivation/$crop'
    | '/history/$id'
    | '/recommendations/compare'
    | '/soil-reports/$id'
    | '/soil-testing/$providerId'
    | '/appointments'
    | '/cultivation'
    | '/history'
    | '/recommendations'
    | '/soil-reports'
    | '/soil-testing'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/ml-evaluation'
    | '/register'
    | '/soil-analysis'
    | '/api/predict'
    | '/appointments/book'
    | '/cultivation/$crop'
    | '/history/$id'
    | '/recommendations/compare'
    | '/soil-reports/$id'
    | '/soil-testing/$providerId'
    | '/appointments/'
    | '/cultivation/'
    | '/history/'
    | '/recommendations/'
    | '/soil-reports/'
    | '/soil-testing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MlEvaluationRoute: typeof MlEvaluationRoute
  RegisterRoute: typeof RegisterRoute
  SoilAnalysisRoute: typeof SoilAnalysisRoute
  ApiPredictRoute: typeof ApiPredictRoute
  AppointmentsBookRoute: typeof AppointmentsBookRoute
  CultivationCropRoute: typeof CultivationCropRoute
  HistoryIdRoute: typeof HistoryIdRoute
  RecommendationsCompareRoute: typeof RecommendationsCompareRoute
  SoilReportsIdRoute: typeof SoilReportsIdRoute
  SoilTestingProviderIdRoute: typeof SoilTestingProviderIdRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
  CultivationIndexRoute: typeof CultivationIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  RecommendationsIndexRoute: typeof RecommendationsIndexRoute
  SoilReportsIndexRoute: typeof SoilReportsIndexRoute
  SoilTestingIndexRoute: typeof SoilTestingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-evaluation': {
      id: '/ml-evaluation'
      path: '/ml-evaluation'
      fullPath: '/ml-evaluation'
      preLoaderRoute: typeof MlEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soil-analysis': {
      id: '/soil-analysis'
      path: '/soil-analysis'
      fullPath: '/soil-analysis'
      preLoaderRoute: typeof SoilAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/predict': {
      id: '/api/predict'
      path: '/api/predict'
      fullPath: '/api/predict'
      preLoaderRoute: typeof ApiPredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/book': {
      id: '/appointments/book'
      path: '/appointments/book'
      fullPath: '/appointments/book'
      preLoaderRoute: typeof AppointmentsBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultivation/': {
      id: '/cultivation/'
      path: '/cultivation'
      fullPath: '/cultivation/'
      preLoaderRoute: typeof CultivationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultivation/$crop': {
      id: '/cultivation/$crop'
      path: '/cultivation/$crop'
      fullPath: '/cultivation/$crop'
      preLoaderRoute: typeof CultivationCropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations/': {
      id: '/recommendations/'
      path: '/recommendations'
      fullPath: '/recommendations/'
      preLoaderRoute: typeof RecommendationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations/compare': {
      id: '/recommendations/compare'
      path: '/recommendations/compare'
      fullPath: '/recommendations/compare'
      preLoaderRoute: typeof RecommendationsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soil-reports/': {
      id: '/soil-reports/'
      path: '/soil-reports'
      fullPath: '/soil-reports/'
      preLoaderRoute: typeof SoilReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soil-reports/$id': {
      id: '/soil-reports/$id'
      path: '/soil-reports/$id'
      fullPath: '/soil-reports/$id'
      preLoaderRoute: typeof SoilReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soil-testing/': {
      id: '/soil-testing/'
      path: '/soil-testing'
      fullPath: '/soil-testing/'
      preLoaderRoute: typeof SoilTestingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soil-testing/$providerId': {
      id: '/soil-testing/$providerId'
      path: '/soil-testing/$providerId'
      fullPath: '/soil-testing/$providerId'
      preLoaderRoute: typeof SoilTestingProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MlEvaluationRoute: MlEvaluationRoute,
  RegisterRoute: RegisterRoute,
  SoilAnalysisRoute: SoilAnalysisRoute,
  ApiPredictRoute: ApiPredictRoute,
  AppointmentsBookRoute: AppointmentsBookRoute,
  CultivationCropRoute: CultivationCropRoute,
  HistoryIdRoute: HistoryIdRoute,
  RecommendationsCompareRoute: RecommendationsCompareRoute,
  SoilReportsIdRoute: SoilReportsIdRoute,
  SoilTestingProviderIdRoute: SoilTestingProviderIdRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
  CultivationIndexRoute: CultivationIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  RecommendationsIndexRoute: RecommendationsIndexRoute,
  SoilReportsIndexRoute: SoilReportsIndexRoute,
  SoilTestingIndexRoute: SoilTestingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
